version: '3.1'

services:
  nginx:
    container_name: ${DOCKER_CONTAINER_PREFIX}nginx
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    container_name: ${DOCKER_CONTAINER_PREFIX}php
    build: ./docker/php
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - $HOME/.composer/cache:/root/.composer/cache
    links:
      - mysql
      - redis
  
  cli:
    container_name: ${DOCKER_CONTAINER_PREFIX}cli
    build: ./docker/cli
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
      - mysql
      - redis

  redis:
    container_name: ${DOCKER_CONTAINER_PREFIX}redis
    image: redis:3.2-alpine

  mysql:
    container_name: ${DOCKER_CONTAINER_PREFIX}mysql
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306

volumes:
  mysql-data:
    driver: local
